apiVersion: v1
kind: Service
metadata: 
  name: todo-load-balancer
  labels:
    app: todo
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 8000
