apiVersion: v1
kind: Service
metadata: 
  name: todo-service
  labels: 
   app: todo-app
spec: 
  type: ClusterIP
  selector:
    app: todo-app
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 8000
      
